application: flashvolunteer
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets  

- url: /test.*
  script: gaeunit.py
  login: admin

- url: /.*
  script: controllers/route.py
  #login: admin
