application: flashvolunteer
version: v02-06
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets  

- url: /test.*
  script: gaeunit.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin    

- url: /appengine_admin_media
  static_dir: components/appengine_admin/media
  secure: never
  
- url: /admin/cron_jobs/.*
  script: controllers/admin/route.py
  login: admin

- url: /admin/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
 
- url: /admin
  script: controllers/admin/route.py
  
- url: /admin/.*
  script: controllers/admin/route.py
    
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /google/.*
  script: controllers/google_api/route.py
          
- url: /.*
  script: controllers/route.py

- url: /favicon.ico
  static_files: stylesheets/favicon.ico
  upload: stylesheets/favicon.ico

admin_console:
 pages:
 - name: Appstats
   url: /admin/stats

