application: flashvolunteer
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets  

- url: /test
  script: tests/unit.py
  login: admin

- url: /.*
  script: controllers/home.py
  login: admin
